name: CI

on:
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f # v4.2.2

    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0

    - name: Run tests
      run: go test ./...
