name: CI

on:
  pull_request:
    types:
      - edited
      - opened
      - ready_for_review
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.2.2

    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0

    - name: Run tests
      run: go test ./...
